web/router.ex
defmodule Main.Router do
  use Main.Web, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true  # Add this
  end

  scope "/" do
    pipe_through :browser
    coherence_routes
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected

    get "/app", Main.AppController, :index
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Main do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/offices", OfficeController
  end

  #Other scopes may use custom stacks.
  scope "/api", Main do
    pipe_through :api

    scope "/v1", as: :v1 do
      resources "/offices", Api.V1.OfficeController, only: [:index, :show]
    end
  end
end

web/views/coherence/layout_view.ex
defmodule Coherence.LayoutView do
  use Main.Coherence.Web, :view


end

web/views/layout_view.ex
defmodule Main.LayoutView do
  use Main.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Main!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/components.css") %>">
    <script src="<%= static_path(@conn, "/js/app.js") %>" defer></script>
  </head>

  <body>
    <div class="wrapper">
      <nav class="navbar navbar-default">
        <a href="#" class="navbar-brand ururu-logo-wrapper" title="Ururu Office">
          <img src="images/ururu_logo.svg" />
        </a>
        <ul class="nav navbar-nav pull-right">
          <%= if @current_user do %>
            <!--<li><%= link("Offices", to: office_path(@conn, :index)) %></li>-->
            <li><%= link("Log out", to: session_path(@conn, :delete), method: "delete") %></li>
          <%= else %>
            <li><%= link("Sign Up", to: registration_path(@conn, :new)) %></li>
            <li><%= link("Sign In", to: session_path(@conn, :new)) %></li>
          <%= end %>
        </ul>
      </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div>
  </body>
</html>